### PR TITLE
Add schema migrations to 5.0.0

### PR DESCRIPTION
**Pull request by juliogonzalez**
Basically we add the migrations from the current version for each schema package from the last tagged 4.4.X version to 5.0.0

Unless I am very wrong, unlike the in the past, this is the only migration we should be needing in this particular case, as we skipped 4.4 for SUSE Manager.

So basically:

# reportdb

- Uyuni users migrating from the last Uyuni released version will go from [4.4.6](https://github.com/uyuni-project/uyuni/blob/master/schema/reportdb/uyuni-reportdb-schema.spec#L27) schema version  to 5.0.0, while others migrating from old versions they will go from their schema that version to 4.4.6 and from there to 5.0.0
- SUSE Manager users will go from their 4.3.X schema version to 4.4.0, from there to 4.4.6 and from there to 5.0.0

# susemanager-schema

- Uyuni users migrating from the last Uyuni released version will go from [4.4.9](https://github.com/uyuni-project/uyuni/blob/master/schema/spacewalk/susemanager-schema.spec#L27) schema version  to 5.0.0, while others migrating from old versions they will go from their schema version to 4.4.9 and from there to 5.0.0
- SUSE Manager users will go from their 4.3.X schema version to 4.4.0, from there to 4.4.9 and from there to 5.0.0

### CODE REVIEW

**Review by mcalmer — CHANGES_REQUESTED** [review]
I think one is wrong. Should one be 4.**3**.X ?

**Review by deneb-alpha — APPROVED** [review]
I  think the  changes are fine and we don't need  any  extra changelog entry  because I have both in my branch already.

**Comment by juliogonzalez** [comment]
> I think one is wrong. Should one be 4.**3**.X ?

What do you mean? Both SPECS at master show 4.4.X for both reportdb and the main schema.

**Comment by juliogonzalez** [comment]
> > I think one is wrong. Should one be 4.**3**.X ?
> 
> What do you mean? Both SPECS at master show 4.4.X for both reportdb and the main schema.

So to be clear I am basically not allowing direct migrations from 4.3.X to 5.0.X as even if for SUSE Manager we never released 4.4, the master branch has 4.4.X migrations that need to be applied.

**Comment by mcalmer** [comment]
> > I think one is wrong. Should one be 4.**3**.X ?
> 
> What do you mean? Both SPECS at master show 4.4.X for both reportdb and the main schema.

Ahh, I overlooked that this was for both schemas.

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
